name: CardReaderProviderApi
options:
  bundleIdPrefix: de.silpion.ti.cardreader.provider
  deploymentTarget:
    macOS: 10.15
    iOS: 17.2
settings:
  base:
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: 67X5G8WXSG
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  CardReaderProviderApi:
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/CardReaderProviderApi
    info:
      path: Resources/CardReaderProviderApi_Info.plist
    dependencies:
      - framework: "Carthage/Build/GemCommonsKit.xcframework"
    scheme:
      testTargets:
        - CardReaderProviderApiTests_${platform}
      gatherCoverageData: true
  CardReaderAccess:
    type: framework
    platform: [iOS,macOS]
    sources:
      - Sources/CardReaderAccess
    info:
      path: Resources/CardReaderAccess_Info.plist
    dependencies:
      - target: CardReaderProviderApi_${platform}
      - framework: "Carthage/Build/GemCommonsKit.xcframework"
    scheme:
      testTargets:
        - CardReaderAccessTests_${platform}
      gatherCoverageData: true
  CardReaderProviderApiTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    sources:
      - Tests/CardReaderProviderApiTests
    dependencies:
      - target: CardReaderProviderApi_${platform}
      - framework: "Carthage/Build/Nimble.xcframework"
  CardReaderAccessTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    sources:
      - Tests/CardReaderAccessTests
    dependencies:
      - target: CardReaderAccess_${platform}
      - target: CardReaderProviderApi_${platform}
      - framework: "Carthage/Build/Nimble.xcframework"
buildImplicitDependencies: true
